INTERESTS = [
    ("Hiking", "Outdoors"),
    ("Camping", "Outdoors"),
    ("Cycling", "Outdoors"),
    ("Running", "Fitness"),
    ("Yoga", "Fitness"),
    ("Gym", "Fitness"),
    ("Cooking", "Food"),
    ("Baking", "Food"),
    ("Coffee", "Food"),
    ("Wine tasting", "Food"),
    ("Street food", "Food"),
    ("Travel", "Travel"),
    ("Backpacking", "Travel"),
    ("Road trips", "Travel"),
    ("Photography", "Art"),
    ("Painting", "Art"),
    ("Dancing", "Art"),
    ("Live music", "Music"),
    ("Singing", "Music"),
    ("Guitar", "Music"),
    ("Movies", "Entertainment"),
    ("Stand-up comedy", "Entertainment"),
    ("Anime", "Entertainment"),
    ("Reading", "Reading"),
    ("Poetry", "Reading"),
    ("Board games", "Gaming"),
    ("Video games", "Gaming"),
    ("Chess", "Gaming"),
    ("Cricket", "Sports"),
    ("Football", "Sports"),
    ("Basketball", "Sports"),
    ("Badminton", "Sports"),
    ("Swimming", "Sports"),
    ("Dogs", "Pets"),
    ("Cats", "Pets"),
    ("Volunteering", "Lifestyle"),
    ("Meditation", "Lifestyle"),
    ("Astrology", "Lifestyle"),
    ("Startups", "Career"),
    ("Tech", "Career"),
    ("Investing", "Career"),
]
